### ISSUE TITLE
[Feature Request] Support for HaxchiFW

### ISSUE THREAD

**Issue by greenDarkness** [Ryuzaki-MrL/savemii#1]
Is there anyway you would consider adding support for HaxchiFW? Currently there aren't any save managers for Wii U that don't require internet access and work with HaxchiFW.

After launching HaxchiFW and then attempting to boot Savemii from the Homebrew menu it black screens on 5.5.1U  Homebrew Menu 2.1 

I should also note that I didn't have it hooked up to a Tv when I tested this, but I'm assuming the menu would appear on both screens.

Thank you for your work, and for reading.

**Comment by linusfessler** [comment]
I'm also using HaxchiFW and had a black screen too when I tried this. However, you can just launch mocha (https://github.com/dimok789/mocha/releases) from the homebrew menu, then it will work.

Still, support for HaxchiFW would be great. And thank you for your work, my hard drive died but your tool helped me recover my BOTW save!

**Comment by greenDarkness** [comment]
@linusfessler Thanks! That worked for me!

**Comment by Ryuzaki-MrL** [comment]
Yeah, I do plan on supporting HaxchiFW. Looking on the homebrew appstore, I noticed that FTPiiU_Everywhere has a separate version for HaxchiFW, but I couldn't find the source code for it. I'll try asking FIX94.

**Comment by shinji257** [comment]
If you didn't find it already I found it on FIX94's github fork for ftpiiu.  It's a separate branch so it wasn't immediately obvious.

https://github.com/FIX94/ftpiiu/tree/ftpiiu_everywhere

**Comment by GabyPCgeeK** [comment]
Seems that I got it working on haxchi (at least on CBHC). Seems that it was crashing when calling MCP_TitleCount after MCPHookOpen was called. So just called MCP_TitleCount before MCPHookOpen and it works. (This is the order in the haxchi installer.)

Added this fix to my fork of savemii
https://github.com/GabyPCgeeK/savemii

**Comment by GabyPCgeeK** [comment]
Also:
Needs more testing but it seems that I got file restoring (when file didn't exist previously) working.

**Comment by djskual** [comment]
pull request #3
