### ISSUE TITLE
Can not delete save data after restoring

### ISSUE THREAD

**Issue by BlackArmsGeneral** [Ryuzaki-MrL/savemii#2]
Honestly, this might be a one time fluke, but after restoring my baked up save data for Super Smash Bros, the game would no longer boot. Wiping the data inside of Savemii does nothing and trying to delete it in the system menu results in a "The data could not be deleted" error.

At this point my only option  is to format my usb hard drive and re download all of my games.

Will provide more info if it is needed, not sure what else to include right now.

**Comment by Ryuzaki-MrL** [comment]
Deleting the savefile with ftpiiu_everywhere may work.
storage_usb:/save/00050000/<titleid for super smash bros>

I'm still looking into why this happens to some games.

**Comment by djskual** [comment]
please merge #3
